hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/skladDb
hibernate.connection.username=postgres
hibernate.connection.password=ZSsazava12
hibernate.default_schema=public